### ISSUE TITLE
To get it to work for me:

### ISSUE THREAD

**Issue by odunbar** [mattlevine22/orthogonal_model_error#1]
To get the code running:
i used a fresh environment. It required `matplotlib`, `scikit-learn`, `seaborn`, `cvxpy`,`tqdm` packages

To get the `example_3d_l63_v2.py` running: `rf_new` -> `rf` here
https://github.com/mattlevine22/orthogonal_model_error/blob/2f5321b04d0742c3826bd75f974e279e453cf3a2/example_3d_l63_v2.py#L3

Cheers matt

**Comment by mattlevine22** [comment]
Removed dependency on `seaborn` and made the following packages optional: `scikit-learn` and `cvxpy` (these are non-default optimization methods for regression). Erroneous usage of `rf_new` has been fixed. 
Still requires `tqdm` and `matplotlib`.
